### ISSUE TITLE
Which discussion platform to use.

### ISSUE THREAD

**Issue by robshep** [NorthWalesTech/NorthWalesTech#1]
We need a platform to maintain many concurrent discussions on varied topics like event planning, chat amongst organisers, general interest chat etc.  

Some users don't use Facebook which was discussed recently.  

**In this issue.... Explore other alternatives.**
Please post alternatives with a rounded pros and cons arguments.  
Please vote using +1 or -1 comments on any that you see in the desc or comments...

- **Facebook**
 - + ubiquitous and the default.
 - + really good for the general public to see what's going on at a glance
 - - not great for long running discussions.

- **Google Groups** (Old one still here north-wales-tech@googlegroups.com https://groups.google.com/d/forum/north-wales-tech)
  - + Web & email 
  - + should be readily adoptable
  - + threaded
  - - outdated and not so social

* **Disqus**  ( trial channel here: https://disqus.com/home/channel/northwalestech/ )
  - + has an app
  - + nice website integrations
  - + Email notifications
  - + nice social features.

* **Slack**
  - - Terrible for threaded discussions. 
  - + good integrations and apps 

* **GitHub Issues and comments** (This is what JSOxford use)
  - - not so inclusive or obvious
  - - not very social
  - - not threaded
  - + good as a mgmt/decision-making record as it can be closed after a decision has been made.

### Please post others and Vote!

*If we start some trial setups, remember to delete them or mark them inactive!*

**Comment by carwyn** [comment]
NOT Github Issues, although it may do for action tracking.

I think facebook is inevitable, although I'd prefer Ye Olde Mailing List (Google Groups can do this).

**Comment by robshep** [comment]
I wonder if facebook is the natural fit for "general interest chat" E.g. 
> Hey, look at this tech I just found! Who's using it

... but then a different group/list/forum for us organisers to hold proper discussions that fb isn't as good for?

**Comment by carwyn** [comment]
+1 Github for admin, labels might be enough rather than distinct repos though?

**Comment by carwyn** [comment]
Prod @davehun since he's in Facebook Exile.

**Comment by carwyn** [comment]
I'm liking the idea of Disqus hung off a statically generated site.

**Comment by spikeheap** [comment]
It's probably worth highlighting the difference between chat, dissemination and discussion – chat such as IRC, Slack, etc. is great for engagement, but it (in our experience) isn't as suitable for organisational decisions and discussion where people might be involved but working on different timescales. We found that newcomers and helpers were a bit put off by seeing high volumes of chat about organisational decisions when they weren't able to respond even though they cared about the topic.

At JSOxford we use [Gitter](https://gitter.im/jsoxford/jsoxford.github.com) for chat, and GitHub for organisational discussion and event management. Gitter has been amazing for getting more people involved and making everything a bit more fun, especially as a few of us work remotely. GitHub has been great for everything else, particularly including speakers and other interested parties in the thread.

We chose Gitter over IRC and Slack because it _feels_ more open to people. We dropped our Gitter link [on the JSOxford homepage](http://jsoxford.com) and on our [GitHub Readme](https://github.com/jsoxford/jsoxford.github.com) – I'd recommend aiming for that level of simplicity for new users. The UI isn't amazing (though it is improving) and it really is a PITA at times, but it doesn't come with the caveats of IRC, and we have seen new members pop up there with questions. Slack has by far the best user experience of any chat client I've seen, but you need to set up [slackin](http://rauchg.com/slackin/) to make it public. 

It seems like Facebook works pretty well for things that sit half-way between chat and proper discussion, so it might serve you well until you have too much noise on it.

The only other thing I'd chime in with is that we've had much more success with really simple processes and systems. Our site repo serves as the only JSOxford issue tracker, holding events, website changes, logo discussion, etc. so I'd +1 Carwyn's single-repo comment.

**Comment by spikeheap** [comment]
One last comment on GitHub issues is that we have actually found them to be the most inclusive and social method (though we haven't used Facebook at all) – pretty much everyone has a GH account, so it's easy to share a link to an issue on Twitter and people can chime in even though they're not part of the group. A great example of that is https://github.com/jsoxford/jsoxford.github.com/issues/107.

**Comment by carwyn** [comment]
There was a reason I set this up https://gitter.im/NorthWalesTech :)

**Comment by carwyn** [comment]
There are a lot of people who don't like Facebook or Google+ hence I don't think we should mandate its use for members to interact. Twitter is a different beast altogether, it's VERY good for tracking activity during an event, plastered on all the walls for people to give instant feedback. I've even seen the hashtag being used to field questions for panel line ups. PyConUK and FlossUK make significant usage of this for example. However even their community groups, much like the old LUGs that are still around, are all still mailman mailing list based.

The one concern I have with Github for our group is that not everyone has an account. There are significant numbers of people I've spoken to that are not yet involved enough in development to have reached this point, so some form of secondary channel seems wise.

Note that Gitter has mobile apps and email notification support, it can also have sub-channels using per repo rooms.

+1 Facebook because we need it for recruitment if nothing else.
+1 GitHub as it's where the development really happens.
+1 Gitter as it's an easy add-on to GitHub

I think encouraging people to interact with a platform like GitHub is a very good idea as these days your GitHub portfolio is arguably more powerful than a CV. Facebook is not at all suitable for this purpose.

I think Twitter is also key but for a different purpose.
